version: '3.8'  # Docker Compose 文件版本

services:  # 定义所有服务
  nginx:  # Nginx服务配置
    image: nginx:alpine  # 使用Nginx Alpine轻量级镜像
    container_name: subscribe-nginx  # 容器名称
    ports:  # 端口映射
      - "8001:8001"
    volumes:  # 卷映射
      - ../nginx/conf.d:/etc/nginx/conf.d  # Nginx配置文件
      - ../nginx/ssl:/etc/nginx/ssl  # SSL证书
      - ../nginx/logs:/var/log/nginx  # Nginx日志
      - ../nginx/html:/usr/share/nginx/html  # 前端静态文件
    restart: unless-stopped  # 除非手动停止，否则总是重启容器